version: "3.8"

services:
  gemini-webui:
    build: .
    container_name: gemini-webui
    ports:
      - "6969:6969"
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    stdin_open: true
    tty: true
