FROM node:20.18.1-slim

# Create app dir
WORKDIR /app

# Copy everything into container
COPY server.js .
COPY public ./public

# Install dependencies
RUN npm install express @google/genai

# Run app
CMD ["node", "server.js"]
